/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2020-06-09 06:34:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import bms.Book;
import util.MyFormat;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1539848608000L));
    _jspx_dependants.put("/common/footer.jsp", Long.valueOf(1539848600000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bms.Book");
    _jspx_imports_classes.add("util.MyFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Book> book_list = (ArrayList<Book>) request
			.getAttribute("book_list");
	MyFormat format = new MyFormat();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>書籍一覧</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\"  href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- ブラウザ全体 -->\r\n");
      out.write("\t\t<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--ヘッダー部分  -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<h1>書籍管理システムWeb版 Ver.1.0</h1>\r\n");
      out.write("</div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- メニュー部分 -->\r\n");
      out.write("\t\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<!-- ナビゲーション  -->\r\n");
      out.write("\t\t\t\t\t<div id=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href =\"");
      out.print(request.getContextPath());
      out.write("/view/menu.jsp\" >[メニュー]</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href =\"");
      out.print(request.getContextPath());
      out.write("/view/insert.jsp\">[書籍登録]</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- ページタイトル -->\r\n");
      out.write("\t\t\t\t\t<div id=\"page_title\">\r\n");
      out.write("\t\t\t\t\t\t<h2>書籍一覧</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 書籍一覧のコンテンツ部分 -->\r\n");
      out.write("\t\t\t<div id=\"main\" class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 検索フォーム -->\r\n");
      out.write("\t\t\t\t<form class=\"inline-block\" action=\"");
      out.print(request.getContextPath());
      out.write("/search\" >\r\n");
      out.write("\t\t \t\t\tISBN <input type=\"text\"  name=\"isbn\">\r\n");
      out.write("\t\t\t\t\tTITLE <input type=\"text\" name=\"title\">\r\n");
      out.write("\t\t\t\t\t価格 <input type=\"text\" name=\"price\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"検索\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form class=\"inline-block\" action=\"");
      out.print(request.getContextPath());
      out.write("/list\" >\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"全件表示\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 書籍情報リスト -->\r\n");
      out.write("\t\t\t\t<table class=\"list-table\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>ISBN</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>TITLE</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>価格</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>変更 / 削除</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");

						if (book_list != null) {
							for (Book book : book_list) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"");
      out.print(request.getContextPath());
      out.write("/detail?isbn=");
      out.print(book.getIsbn());
      out.write("&cmd=detail\">");
      out.print(book.getIsbn() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(book.getTitle() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(format.moneyFormat(book.getPrice()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/detail?isbn=");
      out.print(book.getIsbn());
      out.write("&cmd=update\">変更</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/delete?isbn=");
      out.print(book.getIsbn());
      out.write("\">削除</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/insertIntoCart?isbn=");
      out.print(book.getIsbn());
      out.write("\">カートに入れる</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- フッター部分 -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<h4>Copyright&copy; 2016 All Right Reserved.</h4>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
